# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d19d7508878e2fcc0c798fc1c912b71e31b60ef6a94c7b447a744205ae03eb24ac756004a41608ce5f32f4507513fcf64c67d50c60f2534124fbe52692076cf1

test:
  secret_key_base: d73c32f53820b7871bcff57fff7a3868a4760bf26691aadb4f750f6a4c30641959118a175f9e24e26c8c7c45f790413cb5a1d8f6facc811912ec8d71e750b479

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
